{{- if .Values.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "metricbeat.serviceAccount" . }}-cluster-role
  # Added
  namespace: {{ .Values.namespace | default "kube-system" }}
  labels:
    k8s-app: "{{ template "metricbeat.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
rules: {{ toYaml .Values.clusterRoleRules | nindent 0 }}
{{- end -}}