{{- if .Values.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "metricbeat.serviceAccount" . }}
  namespace: {{ .Values.namespace | default "kube-system" }}
  labels:
    k8s-app: "{{ template "metricbeat.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
subjects:
- kind: ServiceAccount
  name: {{ template "metricbeat.serviceAccount" . }}
  namespace: {{ .Values.namespace | default "kube-system" }}
roleRef:
  kind: Role
  name: {{ template "metricbeat.serviceAccount" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
